name: Shell Coomands

on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello world"
            - name: multiline script
              run: |
                  node -v
                  npm -v
            - name: python command
              run: |
                  import plaform
                  print(plaform.processor())

    run-windows-command:
        runs-on: windows-latest
        steps:
            - name: Directory Powershell
              run: Get-Location
            - name: Directory Bash
              run: pwd
              shell: bash
